#!/bin/sh
set -eu

CONFIG_VARS='${VITE_ENVIRONMENT}
${VITE_ACCESSIBILITY_STATEMENT_URL}
${VITE_GEOID_CLIENT_ID}
${VITE_GEOID_AUTHORITY}
${VITE_GEOID_ISSUER}
${VITE_GEOID_REDIRECT_URI}
${VITE_GEOID_POST_LOGOUT_REDIRECT_URI}
${VITE_GEOID_METADATA_ADDRESS}
${VITE_GEOID_AUTHORIZATION_ENDPOINT}
${VITE_GEOID_TOKEN_ENDPOINT}
${VITE_GEOID_USERINFO_ENDPOINT}
${VITE_GEOID_END_SESSION_ENDPOINT}
${VITE_GEOID_JWKS_URI}
${VITE_GEOID_KID}
${VITE_GEOID_N}
${VITE_GEOID_BAATAUTHZ_APIURL}'

VERSION_VARS='${VITE_BUILD_NUMBER}
${VITE_MAJOR_MINOR_VERSION_MASTER}
${VITE_MAJOR_MINOR_VERSION_DEVELOPMENT}'

if [ -f /etc/app-config/config.js ]; then
    cp /etc/app-config/config.js /tmp/config.js
else
    envsubst "$CONFIG_VARS" < /usr/share/nginx/html/config.template.js > /tmp/config.js
fi

envsubst "$VERSION_VARS" < /usr/share/nginx/html/version.template.js > /tmp/version.js

exec nginx -g 'daemon off;'
