#!/bin/sh
set -eu

CONFIG_VARS='${REACT_APP_ENVIRONMENT}
${REACT_APP_ACCESSIBILITY_STATEMENT_URL}
${REACT_APP_GEOID_CLIENT_ID}
${REACT_APP_GEOID_AUTHORITY}
${REACT_APP_GEOID_ISSUER}
${REACT_APP_GEOID_REDIRECT_URI}
${REACT_APP_GEOID_POST_LOGOUT_REDIRECT_URI}
${REACT_APP_GEOID_METADATA_ADDRESS}
${REACT_APP_GEOID_AUTHORIZATION_ENDPOINT}
${REACT_APP_GEOID_TOKEN_ENDPOINT}
${REACT_APP_GEOID_USERINFO_ENDPOINT}
${REACT_APP_GEOID_END_SESSION_ENDPOINT}
${REACT_APP_GEOID_JWKS_URI}
${REACT_APP_GEOID_KID}
${REACT_APP_GEOID_N}
${REACT_APP_GEOID_BAATAUTHZ_APIURL}'

VERSION_VARS='${REACT_APP_BUILD_NUMBER}
${REACT_APP_MAJOR_MINOR_VERSION_MASTER}
${REACT_APP_MAJOR_MINOR_VERSION_DEVELOPMENT}'

if [ -f /etc/app-config/config.js ]; then
    cp /etc/app-config/config.js /tmp/config.js
else
    envsubst "$CONFIG_VARS" < /usr/share/nginx/html/config.template.js > /tmp/config.js
fi

envsubst "$VERSION_VARS" < /usr/share/nginx/html/version.template.js > /tmp/version.js

exec nginx -g 'daemon off;'
