export const FETCH_MAPITEMS = "FETCH_MAPITEMS";
export const FETCH_ITEMS_TO_DOWNLOAD = "FETCH_ITEMS_TO_DOWNLOAD";

export const FETCH_METADATASEARCHRESULTS = "FETCH_METADATASEARCHRESULTS";
export const FETCH_ARTICLESEARCHRESULTS = "FETCH_ARTICLESEARCHRESULTS";
export const APPEND_TO_ARTICLESEARCHRESULTS = "APPEND_TO_ARTICLESEARCHRESULTS";
export const APPEND_TO_METADATASEARCHRESULTS = "APPEND_TO_METADATASEARCHRESULTS";
export const UPDATE_SELECTEDFACETS = "UPDATE_SELECTEDFACETS";
export const UPDATE_SELECTED_FACETS_FOR_FACET_FIELD = "UPDATE_SELECTED_FACETS_FOR_FACET_FIELD";
export const UPDATE_SELECTED_FACETS_FROM_URL = "UPDATE_SELECTED_FACETS_FROM_URL";
export const ADD_SELECTEDFACET = "ADD_SELECTEDFACET";
export const REMOVE_SELECTEDFACET = "REMOVE_SELECTEDFACET";
export const UPDATE_AVAILABLEFACETS = "UPDATE_AVAILABLEFACETS";
export const UPDATE_EXPANDEDFACETFILTERS = "UPDATE_EXPANDEDFACETFILTERS";
export const UPDATE_SELECTED_SEARCHRESULTS_TYPE = "UPDATE_SELECTED_SEARCHRESULTS_TYPE";
export const UPDATE_SEARCH_STRING = "UPDATE_SEARCH_STRING";
export const UPDATE_SEARCH_STRING_FROM_URL = "UPDATE_SEARCH_STRING_FROM_URL";
export const UPDATE_BAAT_INFO = "UPDATE_BAAT_INFO";
export const FETCH_GEONORGE_MENU = "FETCH_GEONORGE_MENU";
export const FETCH_SELECTED_LANGUAGE = "FETCH_SELECTED_LANGUAGE";
export const FETCH_RESOURCES = "FETCH_RESOURCES";
export const GET_ENVIRONMENT = "GET_ENVIRONMENT";

export const FETCH_AVAILABLE_WFS_SERVICE_STATUSES = "FETCH_AVAILABLE_WFS_SERVICE_STATUSES";
export const FETCH_AVAILABLE_WMS_SERVICE_STATUSES = "FETCH_AVAILABLE_WMS_SERVICE_STATUSES";
