export const FETCH_MAPITEMS = 'FETCH_MAPITEMS';
export const FETCH_METADATASEARCHRESULTS = 'FETCH_METADATASEARCHRESULTS';
export const FETCH_ARTICLESEARCHRESULTS = 'FETCH_ARTICLESEARCHRESULTS';
export const FETCH_DROPDOWNSEARCHRESULTS = 'FETCH_DROPDOWNSEARCHRESULTS';
export const UPDATE_SELECTEDFACETS ='UPDATE_SELECTEDFACETS';
export const ADD_SELECTEDFACET = 'ADD_SELECTEDFACET';
export const REMOVE_SELECTEDFACET = 'REMOVE_SELECTEDFACET';
export const FETCH_AVAILABLEFACETS = 'FETCH_AVAILABLEFACETS';